name: Charts

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a one-line script
        run: |
          curl -L -o main.zip https://github.com/truecharts/catalog/archive/refs/heads/main.zip
          unzip -q main.zip
          rm -f main.zip
          mkdir -p stable
          cp -rf catalog-main/stable/{nextcloud,filerun} stable/
          cp -f catalog-main/{.gitignore,.helmdocsignore,NOTICE,README.md,features_capability.json} .
          jq 'del(.dependency[], .enterprise[], .incubator[], .stable[] | select((.name != "nextcloud") and (.name != "postgresql")))' catalog-main/catalog.json > catalog.json
          rm -rf catalog-main
          
      # Commit changes to repo
      - name: Commit new chart
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Commit new Chart"
          git push
